In [3]:
import numpy as np
import scipy as sp
import sklearn

a = np.array([1,2,3])
a

array([1, 2, 3])

In [6]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [8]:
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [9]:
a = np.array([[1,2,3], [5,6,7]])
a

array([[1, 2, 3],
       [5, 6, 7]])

In [10]:
a
np.zeros_like(a)

array([[0, 0, 0],
       [0, 0, 0]])

In [4]:
np.zeros(2, dtype = int)


array([0, 0])

In [1]:
class NaiveBayes1(object):
    """
    Naive Bayes class (1)
    """
    
    def __init__(self):
        self.pY_ = None
        self.pXgY_ = None
    
    def fit(self. X, y):
        """
        Fitting model
        """
        n_samples = X.shape[0]  # サンプルの数
        n_fertures = X.shape[1] # 特徴数
        n_classes = 2
        n_fvalues = 2
        
        if n_samples != len(y): # サンプル数と正解数が違う場合エラーをはく
            raise ValueError('Mismatched number of samples.')
        
        # クラスの数を数える
        nY = np.zeros(n_classes, dtype=int)
        for i in range(n_samples):
                nY[y[i]] += 1
        
        self.py_ = np.empty(n_classes, dtype=float)
        for i in range(n_classes):
            self.pY_[i] = nY[i] / float(n_samples)
            
        
    
    def predict(self, X):
        """
        Predict class
        """
        pass
    
    